### ISSUE TITLE
I got banned

### ISSUE THREAD

**Issue by thanhdoan1201** [AzagraMac/telegram-kaios#3]
![image](https://github.com/user-attachments/assets/7dbba47b-01ac-4044-8295-fe1610f64deb)
after login 2s, i got banned

**Comment by azagramac** [comment]
Hi, I don't understand what reason they had for banning your phone number. 

I have the same version installed on my Nokia 800 Tough and it works fine.  Talk to telegram support, to see if they can give you more details about your phone number. https://telegram.org/support

regards
